--- 
apiVersion: v1
kind: DeploymentConfig
metadata: 
  labels:
    app: twowayssl
  name: twowayssl
  namespace: rhelnginx
spec: 
  replicas: 2
  selector: 
    app: twowayssl
  strategy: 
    type: Rolling
  template: 
    metadata: 
      labels: 
        app:  twowayssl
    spec: 
      containers: 
        - 
          image: 172.30.163.234:5000/rhelnginx/greentea-nginx
          name: twowayssl
          ports: 
            - 
              containerPort: 443
              protocol: TCP 
  triggers: 
    - 
      type: ConfigChange

